sensor_kit_base_link:
  livox_link:
    x: 0.155
    y: 0.0
    z: 0.067
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  livox_imu_link:
    x: -0.147  # livox_link - 0.008. (https://terra-1-g.djicdn.com/65c028cd298f4669a7f0e40e50ba1131/Livox%20HAP%20(TX)%20User%20Manual.pdf#LD329%20Livox%20HAP%20%28TX%29User%20Manual.indd%3A.28948%3A3504)
    y: 0.0
    z: -0.044  # livox_link - 0.023
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  zed_front/camera_link:
    x: 0.185
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  zed_right/camera_link:
    x: -0.02
    y: -0.145
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: -1.57079633
  zed_rear/camera_link:
    x: -0.185
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: -3.14159265
  zed_left/camera_link:
    x: -0.02
    y: 0.145
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 1.57079633
  yahboom/gnss_link:  # gps receiver
    x: -0.07
    y: -0.09
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  yahboom/imu_link:
    x: -0.075
    y: -0.045
    z: 0.016
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  yahboom/gps_processor_link: # the board that processes received signals. Only needed for visualization
    x: -0.075
    y: -0.045
    z: 0.027
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
