#
---
/**:
    ros__parameters:

        general:
            pub_resolution: 'CUSTOM' # The resolution used for output. 'NATIVE' to use the same `general.grab_resolution` - `CUSTOM` to apply the `general.pub_downscale_factor` downscale factory to reduce bandwidth in transmission
            pub_downscale_factor: 2.0 # rescale factor used to rescale image before publishing when 'pub_resolution' is 'CUSTOM'
            pub_frame_rate: 15.0 # (15.0). frequency of publishing of visual images and depth images
            gpu_id: -1

            # Zed 2i parameters
            grab_resolution: 'HD720' # The native camera grab resolution. 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
            grab_frame_rate: 30 # ZED SDK internal grabbing rate

        depth:
            depth_mode: 'PERFORMANCE' # ('ULTRA'). Matches the ZED SDK setting: 'NONE', 'PERFORMANCE', 'QUALITY', 'ULTRA', 'NEURAL' - Note: if 'NONE' all the modules that requires depth extraction are disabled by default (Pos. Tracking, Obj. Detection, Mapping, ...)
            point_cloud_freq: 10.0 # (10.0). [DYNAMIC] - frequency of the pointcloud publishing (equal or less to `grab_frame_rate` value)

            # Zed 2i parameters
            min_depth: 0.2 # Min: 0.2, Max: 3.0
            max_depth: 40.0 # (10.0). Max: 40.0

#        pos_tracking:
#            publish_tf: false # (true). [usually overwritten by launch file] publish `odom -> base_link` TF
#            publish_map_tf: false # (true). [usually overwritten by launch file] publish `map -> odom` TF
##            two_d_mode: false # Force navigation on a plane. If true the Z value will be fixed to "fixed_z_value", roll and pitch to zero
##            fixed_z_value: 0.00 # Value to be used for Z coordinate if `two_d_mode` is true


        mapping:
            resolution: 0.05 # maps resolution in meters [min: 0.01f - max: 0.2f]
            max_mapping_range: 20.0 # (5.0). maximum depth range while mapping in meters (-1 for automatic calculation) [2.0, 20.0]
            fused_pointcloud_freq: 1.0 # frequency of the publishing of the fused colored point cloud

        sensors:
            sensors_image_sync: false # (false). Synchronize Sensors messages with latest published video/depth message
            sensors_pub_rate: 400. # (200) frequency of publishing of sensors data. MAX: 400. - MIN: grab rate
